# Generated by Django 4.0.6 on 2022-07-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aid',
            new_name='article',
        ),
    ]
